### ISSUE TITLE
Error when trying to clone

### ISSUE THREAD

**Issue by gtalarico** [ADN-DevTech/revit-api-chms#2]
Got error when trying to clone.
Seems like we are out of quota here as well @jeremytammik 
![image](https://user-images.githubusercontent.com/9513968/143985250-ab16057d-30b7-48d4-a39e-54c26cfbdcdc.png)

**Comment by jeremytammik** [comment]
Hi @gtalarico . Sorry about that. Looking into it.

**Comment by jeremytammik** [comment]
Try again now. Maybe the additional data package helped?

**Comment by gtalarico** [comment]
Worked, thanks.
Apidocs.co updates
